Repository ExpTechTW/trem-plugins, pull requests merged in 2025-01, with the labels that each got.

#53 Update eew-source.json
  infos/eew-source.json
Labels: auto-merge, size/XS

#54 Update config.json
  infos/config.json
Labels: auto-merge, size/XS

#55 Update eew-source.json
  infos/eew-source.json
Labels: auto-merge, size/XS

#56 Update eew-source.json
  infos/eew-source.json
Labels: size/S, auto-merge

#57 Update eew-source.json
  infos/eew-source.json
Labels: auto-merge, size/XS

#58 Update websocket.json
  infos/websocket.json
Labels: size/S, auto-merge

#59 Update exptech.json
  infos/exptech.json
Labels: size/S, auto-merge

#60 Update exptech.json
  infos/exptech.json
Labels: auto-merge, size/XS

#61 Update config.json
  infos/config.json
Labels: size/S, auto-merge

#62 Update game-mode.json
  infos/game-mode.json
Labels: size/S, auto-merge

#63 Update game-mode.json
  infos/game-mode.json
Labels: auto-merge, size/XS

#64 Update p-p.json
  infos/p-p.json
Labels: size/S, auto-merge

#65 Update p-p.json
  infos/p-p.json
Labels: auto-merge, size/XS

#66 Update p-p.json
  infos/p-p.json
Labels: auto-merge, size/XS

#67 Update p-p.json
  infos/p-p.json
Labels: auto-merge, size/XS

#68 Update p-p.json
  infos/p-p.json
Labels: auto-merge, size/XS

#69 Update p-p.json
  infos/p-p.json
Labels: auto-merge, size/XS

#70 Update p-p.json
  infos/p-p.json
Labels: auto-merge, size/XS

#71 Update p-p-info.json
  infos/p-p-info.json
Labels: size/S, auto-merge

#72 Update p-p.json
  infos/p-p.json
Labels: auto-merge, size/XS

#73 Update EEW-Logger.json
  infos/EEW-Logger.json
Labels: auto-merge, size/XS

#74 Update p-p-info.json
  infos/p-p-info.json
Labels: auto-merge, size/XS

#75 Update eew-info.json
  infos/eew-info.json
Labels: size/S, auto-merge

#76 Fix track
  .github/workflows/track.yml
Labels: size/S

#77 Update eew-info.json
  infos/eew-info.json
Labels: auto-merge, size/XS

#78 Update eew-info.json
  infos/eew-info.json
Labels: auto-merge, size/XS

#79 Update eew-info.json
  infos/eew-info.json
Labels: auto-merge, size/XS

#80 Update eew-info.json
  infos/eew-info.json
Labels: auto-merge, size/XS

#81 Update eew-info.json
  infos/eew-info.json
Labels: auto-merge, size/XS

#82 Update disable_tts.json
  infos/disable_tts.json
Labels: auto-merge, size/XS

#83 Update disable_tts.json
  infos/disable_tts.json
Labels: auto-merge, size/XS

#85 Update eew-info.json
  infos/eew-info.json
Labels: auto-merge, size/XS

#86 Update websocket.json
  infos/websocket.json
Labels: size/S, auto-merge

#87 Update websocket.json
  infos/websocket.json
Labels: size/S, auto-merge

#88 Update change-tts.json
  infos/change-tts.json
Labels: size/S, auto-merge

#89 Update change-tts.json
  infos/change-tts.json
Labels: auto-merge, size/XS

#90 Update report-limit.json
  infos/report-limit.json
Labels: size/S, auto-merge

#91 Update report-limit.json
  infos/report-limit.json
Labels: auto-merge, size/XS

#92 Update p-p.json
  infos/p-p.json
Labels: auto-merge, size/XS

#93 Update p-p.json
  infos/p-p.json
Labels: auto-merge, size/XS

#94 Update p-p.json
  infos/p-p.json
Labels: auto-merge, size/XS

#96 Update p-p-info.json
  infos/p-p-info.json
Labels: auto-merge, size/XS

#97 Update eew-info.json
  infos/eew-info.json
Labels: auto-merge, size/XS

#98 Update eew-info.json
  infos/eew-info.json
Labels: auto-merge, size/XS

#99 Update eew-info.json
  infos/eew-info.json
Labels: auto-merge, size/XS

#100 Update eew-info.json
  infos/eew-info.json
Labels: auto-merge, size/XS

#101 Update rts-info.json
  infos/rts-info.json
Labels: size/S, auto-merge

#102 Update websocket.json
  infos/websocket.json
Labels: auto-merge, size/XS

#103 Update websocket.json
  infos/websocket.json
Labels: auto-merge, size/XS

#104 Update more-station-info.json
  infos/more-station-info.json
Labels: size/S, auto-merge
